default:
  description: "Default Incus profile"
  config: {}
  devices: {}

nixos-lxc:
  description: "Base NixOS LXC config"
  config:
    boot.autostart: "true"
    limits.cpu: "2"
    limits.memory: "2GiB"
    security.idmap.base: "100000"
    security.idmap.isolated: "true"
    security.idmap.size: "65535"
    security.nesting: "true"
  devices:
    eth0:
      type: "nic"
      nictype: "bridged"
      parent: "br0"
    root:
      type: "disk"
      path: "/"
      pool: "rpool"
      size: "4GiB"

nixos-router-lxc:
  description: "NixOS router LXC config without inherited LAN eth0"
  config:
    boot.autostart: "false"
    limits.cpu: "2"
    limits.memory: "2GiB"
    security.idmap.base: "100000"
    security.idmap.isolated: "true"
    security.idmap.size: "65535"
    security.nesting: "true"
  devices:
    root:
      type: "disk"
      path: "/"
      pool: "rpool"
      size: "4GiB"

downloadHDD-mount:
  description: "Disk passthrough for downloadHDD directory"
  config: {}
  devices:
    downloadHDD:
      type: "disk"
      path: "/mnt/downloadHDD"
      source: "/mnt/downloadHDD"
      shift: "true"

downloadSSD-mount:
  description: "Disk passthrough for downloadSSD directory"
  config: {}
  devices:
    downloadSSD:
      type: "disk"
      path: "/mnt/downloadSSD"
      source: "/mnt/downloadSSD"
      shift: "true"

gamesaves-mount:
  description: "Disk passthrough for gamesaves directory"
  config: {}
  devices:
    gamesaves:
      type: "disk"
      path: "/mnt/zpool/gamesaves"
      source: "/mnt/zpool/gamesaves"
      shift: "true"

gameserver-mount:
  description: "Disk passthrough for gameserver directory"
  config: {}
  devices:
    /mnt/zpool/gameservers:
      type: "disk"
      path: "/mnt/zpool/gameservers"
      source: "/mnt/zpool/gameservers"
      shift: "true"

immich-mount:
  description: "Disk passthrough for immich directory"
  config: {}
  devices:
    downloadHDD:
      type: "disk"
      path: "/mnt/zpool/immich"
      source: "/mnt/zpool/immich"
      shift: "true"

media-mount:
  description: "Disk passthrough for media directory"
  config: {}
  devices:
    /mnt/zpool/media:
      type: "disk"
      path: "/mnt/zpool/media"
      source: "/mnt/zpool/media"
      shift: "true"

nextcloud-mount:
  description: "Disk passthrough for nextcloud directory"
  config: {}
  devices:
    /mnt/zpool/nextcloud:
      type: "disk"
      path: "/mnt/zpool/nextcloud"
      source: "/mnt/zpool/nextcloud"
      shift: "true"

nix-config-mount:
  description: "Disk passthrough for nixos config directory"
  config: {}
  devices:
    /mnt/zpool/code/nix-config:
      type: "disk"
      path: "/mnt/zpool/code/nix-config"
      source: "/mnt/zpool/code/nix-config"
      shift: "true"

roms-mount:
  description: "Disk passthrough for roms directory"
  config: {}
  devices:
    /mnt/zpool/roms:
      type: "disk"
      path: "/mnt/zpool/roms"
      source: "/mnt/zpool/roms"
      shift: "true"
